debug=true
sim_time=500
num_mirrors=25
num_links_per_mirror=2
startup_time_min=5
startup_time_max=10
ready_time_min=2
ready_time_max=20
stop_time_min=2
stop_time_max=5
link_activation_time_min=5
link_activation_time_max=10
fileSize=80
min_bandwidth=2
max_bandwidth=8
fault_probability=0.1
bw_thresh = 15
al_thresh = 15
ttw_thresh = 60
second_bw_thresh = 15
second_al_thresh = 15
second_ttw_thresh = 60
third_bw_thresh = 15
third_al_thresh = 15
third_ttw_thresh = 60
can_fail = false
probability_to_succeed = 100
threshold_change_probability = 0
